apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dashboard
spec:
  selector:
    matchLabels:
      app: flask-dashboardp
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-dashboard
    spec:
      containers:
      - name: flask-dashboard
        image: dvorkinguy/flask-dashboard:29
        ports:
        - containerPort: 5000
